"""RDKit-backed molecular structure generation services."""
from __future__ import annotations

from typing import Any

from rdkit import Chem
from rdkit.Chem import AllChem


INVALID_SMILES_RESPONSE = {"error": "Invalid SMILES string"}


def generate_3d_from_smiles(smiles: str) -> dict[str, Any]:
    """Generate an optimized 3D molecular structure from a SMILES string."""
    normalized = smiles.strip()
    if not normalized:
        return INVALID_SMILES_RESPONSE

    molecule = Chem.MolFromSmiles(normalized)
    if molecule is None:
        return INVALID_SMILES_RESPONSE

    molecule_with_h = Chem.AddHs(molecule)

    conf_ids = _embed_conformers_with_fallback(molecule_with_h)
    if not conf_ids:
        return {"error": "Failed to generate 3D conformer"}

    mmff_props = AllChem.MMFFGetMoleculeProperties(
        molecule_with_h,
        mmffVariant="MMFF94",
    )
    if mmff_props is None:
        return {"error": "MMFF94 parameters unavailable for molecule"}

    best_conf_id, lowest_energy = _optimize_and_rank_conformers(
        molecule_with_h,
        mmff_props,
        conf_ids,
    )
    if best_conf_id is None or lowest_energy is None:
        return {"error": "MMFF94 optimization failed"}

    conformer = molecule_with_h.GetConformer(best_conf_id)
    atoms: list[dict[str, Any]] = []

    for atom in molecule_with_h.GetAtoms():
        atom_index = atom.GetIdx()
        position = conformer.GetAtomPosition(atom_index)
        atoms.append(
            {
                "id": atom_index + 1,
                "element": atom.GetSymbol(),
                "x": round(float(position.x), 6),
                "y": round(float(position.y), 6),
                "z": round(float(position.z), 6),
            }
        )

    return {
        "input_smiles": normalized,
        "atom_count": len(atoms),
        "energy": round(lowest_energy, 6),
        "conformer_count": len(conf_ids),
        "atoms": atoms,
    }


def _embed_conformers_with_fallback(molecule: Chem.Mol) -> list[int]:
    """Embed multiple conformers and fall back to single-conformer embedding."""
    embed_params = AllChem.ETKDGv3()
    embed_params.randomSeed = 0xF00D

    try:
        conf_ids = list(AllChem.EmbedMultipleConfs(molecule, numConfs=5, params=embed_params))
    except Exception:
        conf_ids = []

    if conf_ids:
        return [int(conf_id) for conf_id in conf_ids]

    single_status = AllChem.EmbedMolecule(molecule, embed_params)
    if single_status < 0:
        return []

    return [int(single_status)]


def _optimize_and_rank_conformers(
    molecule: Chem.Mol,
    mmff_props: Any,
    conf_ids: list[int],
) -> tuple[int | None, float | None]:
    """Run MMFF optimization and return the lowest-energy conformer ID and energy."""
    best_conf_id: int | None = None
    lowest_energy: float | None = None

    for conf_id in conf_ids:
        optimize_status = AllChem.MMFFOptimizeMolecule(
            molecule,
            mmffVariant="MMFF94",
            confId=conf_id,
        )
        if optimize_status == -1:
            continue

        force_field = AllChem.MMFFGetMoleculeForceField(
            molecule,
            mmff_props,
            confId=conf_id,
        )
        if force_field is None:
            continue

        energy = float(force_field.CalcEnergy())
        if lowest_energy is None or energy < lowest_energy:
            lowest_energy = energy
            best_conf_id = conf_id

    return best_conf_id, lowest_energy


def mol_to_xyz(mol: Chem.Mol) -> str:
    """Convert an RDKit molecule conformer to XYZ formatted text."""
    if mol is None or mol.GetNumAtoms() == 0 or mol.GetNumConformers() == 0:
        return ""

    conformer = mol.GetConformer()
    lines = [str(mol.GetNumAtoms()), "Generated by MolLens"]

    for atom in mol.GetAtoms():
        position = conformer.GetAtomPosition(atom.GetIdx())
        lines.append(
            f"{atom.GetSymbol()} {position.x:.6f} {position.y:.6f} {position.z:.6f}"
        )

    return "\n".join(lines)
